### ISSUE TITLE
Jobs and hireable persons pages will be added

### ISSUE THREAD

**Issue by alperkaratas** [alperkaratas/find-mentor-mobil#21]

**Comment by alperkaratas** [comment]
Welcome page'e Jobs butonu koyup yönlendirme sağlayarak yeni bi tab navigator'ı olan sayfaya yönlendirdim. Jobs ve JobSeekers adlı tab ekledim. Genel routing yapısı oluşmuş oldu, sayfaların içleri doldurulacak.

**Comment by saracalihan** [comment]
@saracalihan  Job Seekers: https://github.com/alperkaratas/find-mentor-mobil/pull/25

**Comment by saracalihan** [comment]
@saracalihan Jobs Page: https://github.com/alperkaratas/find-mentor-mobil/pull/26

**Comment by saracalihan** [comment]
Done
