### ISSUE TITLE
Profile page will be edited

### ISSUE THREAD

**Issue by alperkaratas** [alperkaratas/find-mentor-mobil#7]

**Comment by alperkaratas** [comment]
Editleyerek genel görünümü elde ettim. **GitHub kullanıcı ReadMe, Active Mentorships, Contributed, Tweets** alanlarının içleri doldurulacak.

**Comment by saracalihan** [comment]
@saracalihan  Tweets & Contributed: https://github.com/alperkaratas/find-mentor-mobil/pull/24
